development: &development
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  socket: /var/run/mysqld/mysqld.sock
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password: root
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_test

production: &production
  adapter: mysql2
  host: localhost
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_production
  username: your_production_database_login
  password: your_production_database_password
